// AUTO-GENERATED by scripts/codegen-permissions.mjs — do not edit.
// Source: ../leo-api/src/modules/identity/constants/permission-matrix.ts

export type Permission =
  | "affiliations:invite"
  | "affiliations:read"
  | "affiliations:request"
  | "affiliations:self:patch"
  | "affiliations:tenant:patch"
  | "auth:switch-tenant"
  | "catalog:certifications:read"
  | "catalog:certifications:write"
  | "catalog:languages:read"
  | "catalog:languages:write"
  | "invitations:create"
  | "memberships:read"
  | "memberships:role:patch"
  | "orgs:read"
  | "orgs:write"
  | "users:read"
  | "users:status:patch"
  | "users:write";

export type CanonicalRole =
  | "customer_admin"
  | "customer_user"
  | "interpreter"
  | "lsp_admin"
  | "platform_admin"
  | "sub_admin";

export const ROLE_PERMISSION_MATRIX: Record<
  CanonicalRole,
  readonly Permission[]
> = {
  customer_admin: [
    "auth:switch-tenant",
    "memberships:read",
    "orgs:read",
    "orgs:write",
    "users:read",
    "invitations:create",
    "catalog:languages:read",
    "catalog:certifications:read",
    "memberships:role:patch",
  ] as const,
  customer_user: [
    "auth:switch-tenant",
    "memberships:read",
    "orgs:read",
    "catalog:languages:read",
    "catalog:certifications:read",
  ] as const,
  interpreter: [
    "auth:switch-tenant",
    "memberships:read",
    "catalog:languages:read",
    "catalog:certifications:read",
    "affiliations:request",
    "affiliations:self:patch",
    "affiliations:read",
  ] as const,
  lsp_admin: [
    "auth:switch-tenant",
    "memberships:read",
    "orgs:read",
    "orgs:write",
    "users:read",
    "users:write",
    "users:status:patch",
    "invitations:create",
    "catalog:languages:read",
    "catalog:certifications:read",
    "affiliations:invite",
    "affiliations:tenant:patch",
    "affiliations:read",
    "memberships:role:patch",
  ] as const,
  platform_admin: [
    "auth:switch-tenant",
    "memberships:read",
    "orgs:read",
    "orgs:write",
    "users:read",
    "users:write",
    "users:status:patch",
    "invitations:create",
    "catalog:languages:read",
    "catalog:languages:write",
    "catalog:certifications:read",
    "catalog:certifications:write",
    "affiliations:read",
  ] as const,
  sub_admin: [
    "auth:switch-tenant",
    "memberships:read",
    "orgs:read",
    "users:read",
    "catalog:languages:read",
    "catalog:certifications:read",
    "affiliations:invite",
    "affiliations:tenant:patch",
    "affiliations:read",
  ] as const,
};

export function hasPermission(
  role: string,
  permission: Permission,
): boolean {
  const grants = ROLE_PERMISSION_MATRIX[role as CanonicalRole];
  if (!grants) return false;
  return grants.includes(permission);
}
